[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[workspace.build-variants]
variant = ["tsan_freethreading"]
abi_tag = ["cp315t"]
version = ["3.15"]

[package.build.backend]
name = "pixi-build-rattler-build"
version = "*"
