name: TestsMSI

on:
  push:
    branches:
    - master
    - 3.10
    - 3.9
    - 3.8
    - 3.7
    paths:
    - 'Tools/msi/**'
    - '.github/workflows/build_msi.yml'
  pull_request:
    branches:
    - master
    - 3.10
    - 3.9
    - 3.8
    - 3.7
    paths:
    - 'Tools/msi/**'
    - '.github/workflows/build_msi.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_win32:
    name: 'Windows (x86) Installer'
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
    - name: Build CPython installer
      run: .\Tools\msi\build.bat --doc -x86

  build_win_amd64:
    name: 'Windows (x64) Installer'
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
    - name: Build CPython installer
      run: .\Tools\msi\build.bat --doc -x64
