name: Check labels

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  label:
    name: DO-NOT-MERGE
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: mheap/github-action-required-labels@v4
        with:
          mode: exactly
          count: 0
          labels: "DO-NOT-MERGE"
